### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by RootYQ** [sh1k4ku/wxapkg#1]
`/www/tmp/node_modules/vm2/lib/transformer.js:86
                throw e;
                ^

vm.js:737
}
^

SyntaxError: Unexpected token '}'
    at makeNiceSyntaxError (/www/tmp/node_modules/vm2/lib/transformer.js:41:16)
    at transformer (/www/tmp/node_modules/vm2/lib/transformer.js:84:8)
    at VM.run (/www/tmp/node_modules/vm2/lib/vm.js:496:16)
    at /www/tmp/wxapkg/wuWxml.js:399:16
    at /www/tmp/wxapkg/wuRestoreZ.js:280:21
    at catchZGroup (/www/tmp/wxapkg/wuRestoreZ.js:16:2)
    at catchZ (/www/tmp/wxapkg/wuRestoreZ.js:21:33)
    at getZ (/www/tmp/wxapkg/wuRestoreZ.js:280:3)
    at /www/tmp/wxapkg/wuWxml.js:382:9
    at /www/tmp/wxapkg/wuLib.js:103:14`

请教这个问题有遇到、有办法解决吗

**Comment by sh1k4ku** [comment]
似乎是在/www/tmp/node_modules/vm2/lib/transformer.js文件中第86行有一个多余的"}"，删除掉试试呢


是非宅
***@***.***

四川大学


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sh1k4ku/wxapkg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月19日(星期三) 晚上6:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[sh1k4ku/wxapkg] 运行报错 (Issue #1)





 
`/www/tmp/node_modules/vm2/lib/transformer.js:86
 throw e;
 ^
 
vm.js:737
 }
 ^
 
SyntaxError: Unexpected token '}'
 at makeNiceSyntaxError (/www/tmp/node_modules/vm2/lib/transformer.js:41:16)
 at transformer (/www/tmp/node_modules/vm2/lib/transformer.js:84:8)
 at VM.run (/www/tmp/node_modules/vm2/lib/vm.js:496:16)
 at /www/tmp/wxapkg/wuWxml.js:399:16
 at /www/tmp/wxapkg/wuRestoreZ.js:280:21
 at catchZGroup (/www/tmp/wxapkg/wuRestoreZ.js:16:2)
 at catchZ (/www/tmp/wxapkg/wuRestoreZ.js:21:33)
 at getZ (/www/tmp/wxapkg/wuRestoreZ.js:280:3)
 at /www/tmp/wxapkg/wuWxml.js:382:9
 at /www/tmp/wxapkg/wuLib.js:103:14`
 
请教这个问题有遇到、有办法解决吗

**Comment by RootYQ** [comment]
ok, 好的谢谢
